# Generated by Django 2.2.5 on 2019-09-24 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryNumber', models.IntegerField(max_length=1000000, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('deliveryAdrss', models.CharField(max_length=600)),
                ('deliveryBool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=4, null=True)),
                ('street', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(max_length=10, null=True)),
                ('information', models.CharField(max_length=600, null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('disponibility', models.BooleanField(default=True)),
                ('picture', models.CharField(max_length=600, null=True)),
                ('information', models.CharField(max_length=600)),
                ('idSeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=4, null=True)),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.IntegerField(max_length=10, null=True)),
                ('information', models.CharField(max_length=600, null=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bascket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdNumber', models.IntegerField(max_length=1000000)),
                ('quantity', models.IntegerField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.InfoUser')),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
        ),
    ]
