# Generated by Django 2.2.5 on 2019-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='postalCode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='postalCode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bascket',
            name='cmdNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bascket',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliveryNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
    ]
