# Generated by Django 2.2.5 on 2019-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190926_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='street',
            field=models.CharField(default='contacter client par mail pour info', max_length=200),
        ),
    ]
