# Generated by Django 2.2.5 on 2019-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.ImageField(upload_to='pic/'),
        ),
    ]
