# Generated by Django 2.2.5 on 2019-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190927_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='pic/'),
        ),
    ]
