# Generated by Django 2.2.5 on 2019-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190927_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruit/Légume', 'Fruit/Légume'), ('Produit laitier', 'Produit laitier'), ('Charcuterie', 'Charcuterie'), ('Boisson', 'Boisson'), ('Divers', 'Divers')], default='Divers', max_length=100),
        ),
    ]
