# Generated by Django 2.2.5 on 2019-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190927_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='bascket',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
