language: python
python:
  - '3.6.8'

# safelist
branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=coop.travis

script:
  - python welcome.py